@startuml
'https://plantuml.com/class-diagram

' ============================ AUX ============================

class Verdict {
    +str msg
    +int test_number

    +void __init__(...)
}
note left of Verdict::__init__
Here and further,
_ _init_ _'s signature
will be omitted
as it simply
initializes attributes
end note


class UserSubmittedData {
    +Path path_to_src
    +int submission_id

    +void __init__(...)
}


class ProgrammingLanguageData {
        +void __init__(...)
        +Path convert_to_executable(path_to_src, suggested_exec_name, conversion_opts)
}


' ========================== PROTOCOLS =========================

abstract class TestingProtocols {
    -list conversion_opts_lst
    -list command_line_opts_lst
    -{static} dict return_code_to_error_msg = ...

    +void __init__(...)
    +{abstract} Verdict check(self, user_submitted_data)
    -{static} int run_code(path_to_executable, path_to_input_file, path_to_output_file, command_line_opts))
    -{static} Path generate_universal_dir(initial_number)
    -{static} Path prevent_dir_name_collision(initial_number, format_function)
    -{static} Path generate_output_path(submission_id)
    -{static} Path generate_exec_path(submission_id)
}

TestingProtocols "1" <-- "+1 programming_language_data" ProgrammingLanguageData

class InputOutput {
    -dict input_output_paths_dict

    +void __init__(...)
}

class InputCustomChecker {
    -set input_paths_set
    -Path path_to_checker_exec

    +void __init__(...)
}

class RandomInputCustomChecker {
    -int test_count
    -Path path_to_input_generation_executable
    -Path path_to_checker_exec


    +void __init__(...)
    -{static} Path generate_input_dir(submission_id)
    -set generate_input(self, submission_id)
}

class LimitedWorkSpace {
    -Path path_to_header
    -Path path_to_footer
    -str extension

    +void __init__(...)
    -Path generate_merged_path(self, submission_id)
    -{static} Path generate_unit_file()
    -Path generate_merged(self, user_submitted_data)
}


TestingProtocols <|--- InputCustomChecker
TestingProtocols <|--- RandomInputCustomChecker
TestingProtocols <|--- LimitedWorkSpace
TestingProtocols <|--- InputOutput


' ============================ AUX ============================

class ProblemData {
    +int problem_id
    +set testing_protocols_set

    +void __init__(...)
}

ProblemData "1" <--- "1..*" TestingProtocols


class ExtendedSubmission {
    +void __init__(...)
}

ExtendedSubmission "1" *--- "+problem_data 1" ProblemData
ExtendedSubmission "1" *--- "+user_submitted_ data1" UserSubmittedData

@enduml