@startuml
'https://plantuml.com/activity-diagram-beta

start
:Initiate problem upload;
:Upload statement;
repeat
:Choose protocol scheme;
:Upload correspondent files;
:Choose programming language;
if (Wish to specify command line options?) then (yes)
    :Specify command line options;
else (no)
endif
if (Wish to pecify source conversion to an executable options?) then (yes)
    :Specify command line options;
else (no)
endif
repeat while (Add another protocol?) is (yes)
->no;
stop

@enduml
